### ISSUE TITLE
Hey,bro, take a look,plz~

### ISSUE THREAD

**Issue by Zero-coder** [xf-zhao/Matcha-agent#2]
I just wanted to let you know that there are two positions open in my lab. There is a Post-doc poition and Research assistant position, both related to DRL and cable driven robotics/programming/construction. If you know anyone from your circle please spread the information. Thank you!
http://jobs.tsinghua.edu.cn/project/qhdx/pages/recruit_new/?FM_SYS_ID=qhdx#/post/detail/0D4F7FAC744A4E5F8D82A19F711DC74F
this is for both PhD and MAster degrees (Post doc and Research assistant)

**Comment by xf-zhao** [comment]
Closed since irrelevant.
